# Generated by Django 3.2.2 on 2021-05-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='friends',
        ),
    ]
