# Generated by Django 3.2.2 on 2021-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follows_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('people', 'people'), ('company', 'company')], default='select', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
