# Generated by Django 3.2.2 on 2021-05-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('comment_date',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feed.comments'),
        ),
    ]
