# Generated by Django 3.2.2 on 2021-05-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20210514_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feed.comments'),
        ),
    ]
