# Generated by Django 3.2.2 on 2021-05-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20210514_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='buyurl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postimages', models.FileField(null=True, upload_to='post_pic')),
                ('Imgtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='feed.post')),
            ],
        ),
    ]
