# Generated by Django 3.2.2 on 2021-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210521_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimages',
            old_name='postimages',
            new_name='pimages',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
