# Generated by Django 3.2.2 on 2021-05-30 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210527_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[(1, 'comming soon'), ('Electronics', ((11, 'learing'), (12, 'home'), (13, 'office'))), ('Entertainment', ((21, 'digital'), (22, 'Games'), (23, 'entertain'))), ('Everyday', ((31, 'House'), (32, 'outdoor'), (33, 'office'), (34, 'other')))], default='1', max_length=100),
        ),
    ]
