# Generated by Django 3.2.2 on 2021-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_post_adminchoose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('comming', 'comming soon'), ('Electronics', (('learn', 'learing'), ('home', 'home'), ('office', 'office'))), ('Entertainment', (('dig', 'digital'), ('games', 'Games'), ('enter', 'entertain'))), ('Everyday', (('house', 'House'), ('outdoor', 'outdoor'), ('office', 'office'), ('other', 'other')))], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='pimages',
            field=models.FileField(blank=True, null=True, upload_to='post_pic'),
        ),
    ]
