# Generated by Django 3.2.2 on 2021-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20210531_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
