# Generated by Django 3.2.2 on 2021-06-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('comming', 'comming soon'), ('learn', 'learing'), ('electrical', 'Electrical'), ('fashion', 'Fashion'), ('games', 'Games'), ('house', 'House'), ('office', 'office'), ('outdoor', 'outdoor'), ('other', 'other')], default='1', max_length=100),
        ),
    ]
